name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🛠 Maintenance'
    labels:
      - 'chore'
template: |
  ## Changes
  $CHANGES
  ## Contributors
  $CONTRIBUTORS
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
no-changes-template: '- No changes'
