name: "Bug report"
description: "Report a bug to help us identify and fix issues in the project."
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        - Remember, we only support Windows 11. If you encounter problems on Windows 10, please consider upgrading to Windows 11.
        - For general questions, join our Community-driven [Discord Server](https://discord.gg/RUbZUZyByQ).

  - type: dropdown
    id: affected_part
    attributes:
      label: What part of Winutil are you having issues with?
      options:
        - Program Install Tab
        - Tweaks Tab
        - Config Tab
        - Updates Tab
        - Win11 Creator Tab
    validations:
      required: false

  - type: textarea
    id: issue_description
    attributes:
      label: Provide a clear and concise description of the issue.
    validations:
      required: true

  - type: textarea
    id: error_output
    attributes:
      label: Paste the full error output (if available) or Screenshot.
      placeholder: "Include any relevant logs or error messages."
