blank_issues_enabled: false
contact_links:
    - name: 💻 Community Discord
      url: https://discord.gg/RUbZUZyByQ
      about: Join our Community Discord server to chat with other users in the Winutil community.
