name: "Feature request"
description: "Suggest a new feature or improvement for the project."
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        # ✨ **Feature request**
        Thank you for taking the time to suggest a feature! Please provide as much detail as possible to help us understand and evaluate your request.

        ## ⚠️ **IMPORTANT**
        - 🛠️ **Supported environments only:** We only support Windows 11.
        - 💡 For general questions, use the [Discussions section](https://github.com/Christitustech/winutil/discussions) or join our Community-driven [Discord Server](https://discord.gg/RUbZUZyByQ).

  - type: textarea
    id: proposed_solution
    attributes:
      label: 💡 Describe the solution you'd like
      placeholder: "Provide a clear and concise description."
    validations:
      required: true
