name: Deploy Astro site to Pages

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    if: github.repository == 'ChrisTitusTech/winutil'
    runs-on: ubuntu-latest
    env:
      TZ: America/Chicago
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install, build, and upload your site
        uses: withastro/action@v6
        with:
          path: docs

  deploy:
    if: github.repository == 'ChrisTitusTech/winutil'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
