name: GitHub Pages Deploy

on:
  release:
    types: [published, prereleased]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'  # Fetch all commit history for all branches as well as tags.

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x  # Install latest Stable release of Python 3
          cache: 'pip'  # caching pip dependencies

      - name: Install Necessary Dependencies using 'pip install -r requirements.txt'
        run: pip install -r requirements.txt

      - name: Build & Deploy using 'mkdocs'
        run: mkdocs gh-deploy --force
