name: GitHub Pages Deploy

on:
  push:
    paths:
      - '.github/mkdocs.yml'
      - '.github/requirements.txt'
      - 'docs/**'
      - 'overrides/**'
      - '.github/CONTRIBUTING.md'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'  # Fetch all commit history for all branches as well as tags.

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x  # Install latest Stable release of Python 3
          cache: 'pip'  # Caching pip dependencies

      - name: Install Necessary Dependencies
        run: pip install -r .github/requirements.txt

      - name: Build & Deploy using mkdocs
        run: mkdocs gh-deploy --force -f .github/mkdocs.yml
