name: Repo Contributors' Triage Tools

on:
    issue_comment: 
        types: [created, edited]

jobs:
    triage-tools:
        runs-on: ubuntu-latest
        permissions: 
            issues: write
            pull-requests: write
            contents: read
        steps:
            - name: Process message
              uses: actions/github-script@v9
              with:
                script: |
                    const trustedUsers = ["ChrisTitusTech", "FluffyPunk", "FallenGME", "mewclouds", "MyDrift-user", "Real-MullaC", "CodingWonders", "og-mrk"];
                    const commentAuthor = context.payload.comment.user.login;

                    if (!trustedUsers.includes(commentAuthor)) {
                        console.log(`Comment author ${commentAuthor} is not a trusted user. Exiting.`);
                        return;
                    }

                    const eventType = context.payload.pull_request ? "pull request" : "issue";

                    const comment = context.payload.comment;
                    const {owner, repo} = context.issue;
                    const issueNumber = context.issue.number;

                    const triageMatch = comment.body.match(/\/triage\b/);
                    if (triageMatch) {
                        const issue = await github.rest.issues.get({
                            owner,
                            repo,
                            issue_number: issueNumber
                        });
                        console.log(issue)
                        if (issue.data.labels.some(label => label.name === "needs-triage")) {
                            await github.rest.issues.createComment({
                              owner,
                              repo,
                              issue_number: issueNumber,
                              body: `The ${eventType} already has the 'needs-triage' label. For removing label, do /triageoff.`
                            });
                      } else {
                          await github.rest.issues.addLabels({
                             owner,
                             repo,
                             issue_number: issueNumber,
                             labels: ["needs-triage"]
                          });
                          await github.rest.issues.createComment({
                             owner,
                             repo,
                             issue_number: issueNumber,
                             body: `${commentAuthor} has asked maintainer for a triage on this ${eventType}.`
                          });
                        }
                        await github.rest.issues.deleteComment({
                             owner,
                             repo,
                             comment_id: comment.id
                          });
                        }
                    const triageOffMatch = comment.body.match(/\/triageoff\b/);
                    if (triageOffMatch) {
                        const issue = await github.rest.issues.get({
                            owner,
                            repo,
                            issue_number: issueNumber
                        });
                        if (issue.data.labels.some(label => label.name === "needs-triage")) {
                            await github.rest.issues.removeLabel({
                                owner,
                                repo,
                                issue_number: issueNumber,
                                name: "needs-triage"
                            });
                            await github.rest.issues.createComment({
                                owner,
                                repo,
                                issue_number: issueNumber,
                                body: `${commentAuthor} removed triage request from this issue.`
                            });
                        } else {
                            await github.rest.issues.createComment({
                                owner,
                                repo,
                                issue_number: issueNumber,
                                body: `The issue is not requested for triage.`
                            });
                        }
                        await github.rest.issues.deleteComment({
                            owner,
                            repo,
                            comment_id: comment.id
                        });
                    }
                    const notPlannedMatch = comment.body.match(/\/notplanned\s+(\w+)/);
                    if (notPlannedMatch && eventType === "issue") {
                        switch (notPlannedMatch[1]) {
                            case "wontfix":
                                await eventHolder.update({
                                    owner,
                                    repo,
                                    issue_number: issueNumber,
                                    state: "closed",
                                    state_reason: "not_planned",
                                    labels: ["wontfix"]
                                });
                                await eventHolder.createComment({
                                    owner,
                                    repo,
                                    issue_number: issueNumber,
                                    body: `${commentAuthor} marked this ${eventType} as not fixable`
                                });
                                await eventHolder.removeComment({
                                    owner,
                                    repo,
                                    comment_id: comment.id
                                });
                                break;
                            case "notrelated":
                                await eventHolder.update({
                                    owner,
                                    repo,
                                    issue_number: issueNumber,
                                    state: "closed",
                                    state_reason: "not_planned",
                                    labels: ["not-related"]
                                });
                                await eventHolder.createComment({
                                    owner,
                                    repo,
                                    issue_number: issueNumber,
                                    body: `${commentAuthor} marked this ${eventType} as not related to the project`
                                });
                                await eventHolder.removeComment({
                                    owner,
                                    repo,
                                    comment_id: comment.id
                                });
                                break;
                            default:
                                await eventHolder.createComment({
                                    owner,
                                    repo,
                                    issue_number: issueNumber,
                                    body: `${commentAuthor} marked this ${eventType} as not planned.`
                                });
                                await eventHolder.removeComment({
                                    owner,
                                    repo,
                                    comment_id: comment.id
                                });
                                break;
                        };
                    }
